/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Thu Dec 17 2015 15:00:17 GMT-0800 (PST)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , timeout = require('request-timeout')
  , storageInfraApi = require('./storage.infra.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/storage/', handler_dashboard);
  app.get('/api/monitor/infrastructure/storagenodes/summary', storageInfraApi_getStorageSummary);
  app.get('/api/admin/monitor/infrastructure/storagenodes/summary', storageInfraApi_getStorageSummary);
  app.get('/api/admin/monitor/infrastructure/storagenodes/details', storageInfraApi_getStorageTopologyDetails);
  app.get('/api/admin/monitor/infrastructure/storagenode/disks', storageInfraApi_getStorageNodeDisks);


  parseURLReq.rbac.setFeatureByURL('/api/storage/', 'get', app.routes, 'storage');
  parseURLReq.rbac.setFeatureByURL('/api/monitor/infrastructure/storagenodes/summary', 'get', app.routes, 'storage');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/storagenodes/summary', 'get', app.routes, 'storage');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/storagenodes/details', 'get', app.routes, 'storage');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/storagenode/disks', 'get', app.routes, 'storage');
}
handler_dashboard = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, handler.dashboard);
  }
}
storageInfraApi_getStorageSummary = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, storageInfraApi.getStorageSummary);
  }
}
storageInfraApi_getStorageSummary = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, storageInfraApi.getStorageSummary);
  }
}
storageInfraApi_getStorageTopologyDetails = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, storageInfraApi.getStorageTopologyDetails);
  }
}
storageInfraApi_getStorageNodeDisks = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, storageInfraApi.getStorageNodeDisks);
  }
}
