/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the jobProcess.xml at
   Thu Dec 17 2015 15:00:17 GMT-0800 (PST)
   Please do not edit this file.
 */

var parseJobsReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseJobsRequire')
  , jobsProcess = require('../../../common/api/storage.jobsProcess.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
var jobsCb = module.exports;


var defMaxActiveJobs = 10;
var maxActiveJobs = parseJobsReq.config.maxActiveJobs || defMaxActiveJobs;

jobsCb.jobsProcess = function() {
  parseJobsReq.jobsApi.jobs.process('getStorageSummary', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processStorageSummaryRequestByJob(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });
}

jobsCb.addjobListenerEvent = function() {
}